// Auto-generated by sample_bg_colors.py - DO NOT EDIT
// This file contains bar colors sampled from backgrounds.bin

#ifndef BG_BAR_COLORS_H
#define BG_BAR_COLORS_H

#include <stdint.h>

// Pre-sampled bar colors for each background (bottom-center pixels)
// Order matches BackgroundIndex enum in background_manager.h
static const uint16_t bg_bar_colors[16] = {
    0xC220,  // 0: BG_TIME_DAY
    0x5060,  // 1: BG_TIME_SUNSET
    0xD207,  // 2: BG_TIME_SUNRISE
    0xA100,  // 3: BG_TIME_NIGHT
    0x1882,  // 4: BG_WEATHER_RAINY
    0x88E0,  // 5: BG_FESTIVAL_CHRISTMAS
    0xDA22,  // 6: BG_FESTIVAL_BIRTHDAY
    0xB960,  // 7: BG_FESTIVAL_SPRING
    0xA180,  // 8: BG_FESTIVAL_NEWYEAR
    0xB9E1,  // 9: BG_FESTIVAL_MIDAUTUMN
    0x1823,  // 10: BG_FESTIVAL_HALLOWEEN
    0xCA22,  // 11: BG_FESTIVAL_VALENTINES
    0x0047,  // 12: BG_STYLE_CYBERPUNK
    0x3840,  // 13: BG_STYLE_STEAMPUNK
    0x80E0,  // 14: BG_STYLE_FANTASY
    0x08A7,  // 15: BG_STYLE_SPACE
};

#endif // BG_BAR_COLORS_H
