#!/usr/bin/env python3
"""
Sample bar colors from background images at compile time.

Reads backgrounds.bin and samples the bottom-center color of each background,
then generates a C header file with the RGB565 color values.

Usage:
    python sample_bg_colors.py --input gifs/backgrounds.bin --output main/boards/waveshare-c6-lcd-1.69/bg_bar_colors.h
"""

import argparse
import os
import struct

# Background format constants (must match background_loader.h)
BG_WIDTH = 280
BG_HEIGHT = 240
BG_PALETTE_COLORS = 256
BG_PALETTE_SIZE = BG_PALETTE_COLORS * 3  # 768 bytes (RGB888)
BG_PIXELS_SIZE = BG_WIDTH * BG_HEIGHT    # 67200 bytes
BG_FRAME_SIZE = BG_PALETTE_SIZE + BG_PIXELS_SIZE  # 67968 bytes per frame

# Background names (must match BackgroundIndex enum in background_manager.h)
BG_NAMES = [
    "BG_TIME_DAY",           # 0: 白天
    "BG_TIME_SUNSET",        # 1: 夕阳
    "BG_TIME_SUNRISE",       # 2: 日出
    "BG_TIME_NIGHT",         # 3: 黑夜
    "BG_WEATHER_RAINY",      # 4: 雨天
    "BG_FESTIVAL_CHRISTMAS", # 5: 圣诞
    "BG_FESTIVAL_BIRTHDAY",  # 6: 生日
    "BG_FESTIVAL_SPRING",    # 7: 春节
    "BG_FESTIVAL_NEWYEAR",   # 8: 元旦
    "BG_FESTIVAL_MIDAUTUMN", # 9: 中秋
    "BG_FESTIVAL_HALLOWEEN", # 10: 万圣节
    "BG_FESTIVAL_VALENTINES",# 11: 情人节
    "BG_STYLE_CYBERPUNK",    # 12: 赛博朋克
    "BG_STYLE_STEAMPUNK",    # 13: 蒸汽朋克
    "BG_STYLE_FANTASY",      # 14: 奇幻
    "BG_STYLE_SPACE",        # 15: 太空舱
]

def rgb888_to_rgb565(r, g, b):
    """Convert RGB888 to RGB565"""
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F
    return (r5 << 11) | (g6 << 5) | b5

def sample_background_color(data, bg_index):
    """
    Sample the bottom-center color from a background frame.
    Returns RGB565 color value.
    """
    frame_offset = bg_index * BG_FRAME_SIZE

    # Read palette (RGB888, 256 colors)
    palette = []
    for i in range(BG_PALETTE_COLORS):
        palette_offset = frame_offset + i * 3
        r = data[palette_offset]
        g = data[palette_offset + 1]
        b = data[palette_offset + 2]
        palette.append((r, g, b))

    # Sample bottom-center pixels (y = height - 5, center x)
    sample_y = BG_HEIGHT - 5
    center_x = BG_WIDTH // 2

    r_sum, g_sum, b_sum = 0, 0, 0
    sample_count = 0

    # Sample 5 pixels horizontally at bottom center
    for dx in range(-2, 3):
        x = center_x + dx * 5
        if 0 <= x < BG_WIDTH:
            pixel_offset = frame_offset + BG_PALETTE_SIZE + sample_y * BG_WIDTH + x
            palette_index = data[pixel_offset]
            r, g, b = palette[palette_index]
            r_sum += r
            g_sum += g
            b_sum += b
            sample_count += 1

    if sample_count == 0:
        return 0x0000

    # Average
    r_avg = r_sum // sample_count
    g_avg = g_sum // sample_count
    b_avg = b_sum // sample_count

    return rgb888_to_rgb565(r_avg, g_avg, b_avg)

def generate_header(colors, output_path):
    """Generate C header file with sampled colors"""
    header = """// Auto-generated by sample_bg_colors.py - DO NOT EDIT
// This file contains bar colors sampled from backgrounds.bin

#ifndef BG_BAR_COLORS_H
#define BG_BAR_COLORS_H

#include <stdint.h>

// Pre-sampled bar colors for each background (bottom-center pixels)
// Order matches BackgroundIndex enum in background_manager.h
static const uint16_t bg_bar_colors[16] = {
"""

    for i, color in enumerate(colors):
        name = BG_NAMES[i] if i < len(BG_NAMES) else f"BG_{i}"
        header += f"    0x{color:04X},  // {i}: {name}\n"

    header += """};

#endif // BG_BAR_COLORS_H
"""

    with open(output_path, 'w') as f:
        f.write(header)

    print(f"Generated: {output_path}")

def main():
    parser = argparse.ArgumentParser(description='Sample bar colors from background images')
    parser.add_argument('--input', required=True, help='Path to backgrounds.bin')
    parser.add_argument('--output', required=True, help='Output header file path')
    parser.add_argument('--count', type=int, default=16, help='Number of backgrounds')

    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"Error: Input file not found: {args.input}")
        return 1

    # Read backgrounds.bin
    with open(args.input, 'rb') as f:
        data = f.read()

    print(f"Read {len(data)} bytes from {args.input}")
    print(f"Expected size for {args.count} backgrounds: {args.count * BG_FRAME_SIZE} bytes")

    # Sample colors from each background
    colors = []
    for i in range(args.count):
        if (i + 1) * BG_FRAME_SIZE > len(data):
            print(f"Warning: Not enough data for background {i}, using black")
            colors.append(0x0000)
        else:
            color = sample_background_color(data, i)
            colors.append(color)
            print(f"  Background {i} ({BG_NAMES[i] if i < len(BG_NAMES) else '?'}): 0x{color:04X}")

    # Generate header file
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    generate_header(colors, args.output)

    print(f"\nSuccessfully sampled {len(colors)} background colors")
    return 0

if __name__ == "__main__":
    exit(main())
